import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import MainNavigation from './shared/components/Navigations/MainNavigation'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">  
      <head>
        <title>YourPlace</title>
        <script async defer
          src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDlDVA68l66Pnt0YX_Q-WL1vO1HKdIdDd4&callback=Function.prototype">
        </script>
      </head>
      <body className={inter.className}>
        <div id="drawer-hook"></div>
        <div id="backdrop-hook"></div>
        <div id="modal-hook"></div>
        <MainNavigation />
        <main className='bg-[#2C2F33] min-h-screen'>
          {children}
        </main>
      </body>
    </html>
  )
}
